version: "3.8"

services:
    mysqldb:
        build:
            context: ./
            dockerfile: Dockerfile_mysql
        platform: linux/x86_64
        container_name: filmesapi-mysql
        ports:
            - 3306:3306
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 5s
            retries: 10
    app:
        depends_on:
            mysqldb:
                condition: service_healthy
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /home/node/app
        container_name: filmesapi-loopback
        restart: unless-stopped
        env_file: ./.env
        ports:
            - 8080:3000
        stdin_open: true
        tty: true
    react:
        depends_on:
            mysqldb:
                condition: service_healthy
        build:
            context: ./filmes_react_app
            dockerfile: dockerfile
        working_dir: /app
        container_name: filmesapi-react
        restart: unless-stopped
        env_file: ./.env
        ports:
            - 8081:3000
        stdin_open: true
        tty: true

