FROM mysql:5.7

# Set the environment variables
ENV MYSQL_ROOT_PASSWORD=12345678
ENV MYSQL_DATABASE=Filmes

# Copy the database file into the container at /docker-entrypoint-initdb.d/
COPY ./db.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
