# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Build the React Admin app
RUN npm run build

# Expose port 3000
EXPOSE 3001

# Start the React Admin app
CMD ["npm", "start"]
